[package]
name = "Aternos-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
azalea = "0.13.0"
parking_lot = "0.12.4"
tokio = { version="1.47.1", features = ["full"]}

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
